kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "zeppelin-interpreter-template.fullname" . }}
  labels:
    {{- include "zeppelin-interpreter-template.labels" . | nindent 4 }}
data:
  template.yaml: |
    ---
    {{- include "zeppelin-interpreter-template.service" . | nindent 6 }}
    ---
    {{- include "zeppelin-interpreter-template.pod" . | nindent 6 }}
    {{- if .Values.ingress.enabled }}
    ---
    {{- include "zeppelin-interpreter-template.ingress" . | nindent 6 }}
    {{- end }}