{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "zeppelin.fullname" . }}
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "zeppelin.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # accept traffic from zeppelin to thrift port
  - from:
    - podSelector:
        matchLabels:
          {{- .Values.zeppelin.serviceLabels | toYaml | nindent 10 }}
    ports:
    - protocol: TCP
      port: thrift
  # accept traffic on webui
  - ports:
    - protocol: TCP
      port: webui
    - protocol: TCP
      port: interpreter
  {{- with .Values.networkPolicy.extraIngressRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  egress:
  # communicate with Zeppelin RPC
  - to:
    - podSelector:
        matchLabels:
          {{- .Values.zeppelin.serviceLabels | toYaml | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.zeppelin.rpcPort }}
  {{- with .Values.networkPolicy.extraEgressRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}