apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeppelin.fullname" . }}
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.interpreter.port }}
    targetPort: interpreter
    protocol: TCP
    name: interpreter
  - port: {{ .Values.service.webui.port }}
    targetPort: webui
    protocol: TCP
    name: webui
  - port: {{ .Values.service.thrift.port }}
    targetPort: thrift
    protocol: TCP
    name: thrift
  selector:
    {{- include "zeppelin.selectorLabels" . | nindent 4 }}