{{- if eq .Values.app.kind "spark" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "zeppelin.fullname" . }}-spark
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "zeppelin.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # accept all traffic from Spark cluster
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: master
          app.kubernetes.io/instance: spark-cluster
          app.kubernetes.io/name: spark
  egress:
  # send all traffic to Spark cluster
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: master
          app.kubernetes.io/instance: spark-cluster
          app.kubernetes.io/name: spark
{{- end }}