replicaCount: 1

image:
  repository: apache/zeppelin
  tag: 0.9.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "zep"
  rbac:
    create: false

podAnnotations: {}

podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
     - ALL
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

networkPolicy:
  enabled: true
  extraEgressRules: []
  extraIngressRules: []

service:
  type: ClusterIP
  interpreter:
    port: 8080
  thrift:
    port: 10000
  webui:
    port: 4040

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

artifacts:
  enabled: true

  image:
    repository: bitnami/spark
    tag: 2.4.5
    pullPolicy: IfNotPresent

  copyDirectory: /opt/bitnami/spark

app:
  kind: spark

  jvmMemOptions: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Xms512m -Xmx512m -XX:MaxMetaspaceSize=512m

zeppelin:
  host: zeppelin
  rpcPort: 38853

  serviceLabels:
    app.kubernetes.io/name: zeppelin
    app.kubernetes.io/instance: zeppelin

logging:
  level: INFO
  syslog: {}
    #level: INFO
    #host: 
    #port: 
    #facility:
    #pattern: