{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "spark-history.fullname" . }}
  labels:
    {{- include "spark-history.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "spark-history.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
{{- end }}
