kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "spark-history.fullname" . }}-conf
  labels:
    {{- include "spark-history.labels" . | nindent 4 }}
data:
  spark-defaults.conf: |-
    {{ .Values.sparkConf | toYaml | nindent 4 }}