apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-master.fullname" . }}
  labels:
    {{- include "spark-master.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clusterPort }}
      targetPort: cluster
      name: cluster
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.cluster)) }}
      nodePort: {{ .Values.service.nodePorts.cluster }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - port: {{ .Values.service.webPort }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.web)) }}
      nodePort: {{ .Values.service.nodePorts.web }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector:
    {{- include "spark-master.selectorLabels" . | nindent 4 }}
