{{- $elasticsearchURL := .Values.elasticsearchURL -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "es-proviz.fullname" . }}
  labels:
    {{- include "es-proviz.labels" . | nindent 4 }}
spec:
  {{- with .Values.extraJobSpec }}
    {{- . | toYaml | nindent 2 }}
  {{- end }}
  template:
    metadata:
      {{- if or .Values.vault.enabled .Values.podAnnotations }}
      annotations:
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-init-first: 'true'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: update
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/ca-cert: '/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        vault.hashicorp.com/secret-volume-path: {{ .Values.vault.volumePath }}
        vault.hashicorp.com/role: {{ .Values.vault.role }}
        {{- range .Values.actions }}
        {{- if .vault }}
        vault.hashicorp.com/agent-inject-secret-{{ .name }}: "{{ .vault.key }}"
        vault.hashicorp.com/agent-inject-file-{{ .name }}: {{ include "es-proviz.actionFilename" . }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "es-proviz.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "es-proviz.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        workingDir: {{ .Values.workingDir }}
        command:
        - sh
        args:
        - -c
        - |-
          alias http={{ quote .Values.curlAlias }}

          echo "Hello"
          http {{ $elasticsearchURL }}

          {{- if .Values.vault.enabled }}
          # Copy vault generated resources
          cp -r {{ .Values.vault.volumePath }}/. .
          {{- end }}

          {{ range .Values.actions }}
          echo ""
          echo ""

          {{ if eq .kind "index_template" }}
          # https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates-v1.html
          echo "Removing index template {{ .name }}"
          http -XDELETE {{ $elasticsearchURL }}/_template/{{ .name }}
          echo ""
          echo "Deploy index template {{ .name }}"
          http -XPUT -d @{{ include "es-proviz.actionFilename" . }} {{ $elasticsearchURL }}/_template/{{ .name }}
          
          {{ else if eq .kind "livecycle_policy" }}
          # https://www.elastic.co/guide/en/elasticsearch/reference/7.16/ilm-put-lifecycle.html
          echo "Removing ILM policy {{ .name }}"
          http -XDELETE {{ $elasticsearchURL }}/_ilm/policy/{{ .name }}
          echo ""
          echo "Deploy ILM policy {{ .name }}"
          http -XPUT -d @{{ include "es-proviz.actionFilename" . }} {{ $elasticsearchURL }}/_ilm/policy/{{ .name }}
          
          {{ else if eq .kind "snapshot_repository" }}
          # https://www.elastic.co/guide/en/elasticsearch/reference/current/put-snapshot-repo-api.html
          echo "Removing snapshot repository {{ .name }}"
          http -XDELETE {{ $elasticsearchURL }}/_snapshot/{{ .name }}
          echo ""
          echo "Deploy snapshot repository {{ .name }}"
          http -XPUT -d @{{ include "es-proviz.actionFilename" . }} {{ $elasticsearchURL }}/_snapshot/{{ .name }}
          
          {{ else if eq .kind "slm_policy" }}
          # https://www.elastic.co/guide/en/elasticsearch/reference/master/slm-api-put-policy.html
          echo "Removing SLM policy {{ .name }}"
          http -XDELETE {{ $elasticsearchURL }}/_slm/policy/{{ .name }}
          echo ""
          echo "Deploy SLM policy {{ .name }}"
          http -XPUT -d @{{ include "es-proviz.actionFilename" . }} {{ $elasticsearchURL }}/_slm/policy/{{ .name }}
          
          {{ else if eq .kind "role" }}
          # https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-role.html
          echo "Deploy role {{ .name }}"
          http -XPUT -d @{{ include "es-proviz.actionFilename" . }} {{ $elasticsearchURL }}/_security/role/{{ .name }}
          
          {{ else if eq .kind "role-mapping" }}
          # https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-api-put-role-mapping.html
          echo "Deploy role mapping {{ .name }}"
          http -XPUT -d @{{ include "es-proviz.actionFilename" . }} {{ $elasticsearchURL }}/_security/role_mapping/{{ .name }}
          
          {{ else if eq .kind "user" }}
          # https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html
          echo "Deploy user {{ .name }}"
          http -XPOST -d @{{ include "es-proviz.actionFilename" . }} {{ $elasticsearchURL }}/_security/user/{{ .name }}

          {{ else if eq .kind "user_password" }}
          echo "Deploy user password {{ .name }}"
          http -XPOST -d @{{ include "es-proviz.actionFilename" . }} {{ $elasticsearchURL }}/_security/user/{{ .name }}/_password

          {{ else if eq .kind "user_password_via_env" }}
          echo "Deploy user password {{ .name }}"
          http -XPOST -d "{\"password\" : \"${{ (.spec | fromJson).passwordEnv }}\"}" {{ $elasticsearchURL }}/_security/user/${{ (.spec | fromJson).usernameEnv }}/_password
          
          {{- end }}

          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.actions }}
        volumeMounts:
          - name: script-files
            mountPath: {{ .Values.workingDir }}
        {{- end }}
        {{- with .Values.extraEnvs }}
        env: {{ . | toYaml | nindent 10}}
        {{- end }}
      restartPolicy: Never
      {{- if .Values.actions }}
      volumes:
      - name: script-files
        configMap:
          name: {{ include "es-proviz.fullname" . }}
      {{- end }}