{{- if .Values.networkPolicyEgress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "es-proviz.fullname" . }}
  labels:
    {{- include "es-proviz.labels" . | nindent 4 }}
spec:
  egress: 
  - ports:
    - port: {{ .Values.networkPolicyEgress.port }}
      protocol: TCP
    to:
      {{- .Values.networkPolicyEgress.to | toYaml | nindent 6 }}
  podSelector:
    matchLabels:
      {{- include "es-proviz.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
{{- end }}