annotations:
  category: Analytics
apiVersion: v2
name: zeppelin
description: Apache Zeppelin with Apache Spark
type: application
version: 0.4.1
appVersion: 0.10.1
engine: gotpl
home: https://github.com/ebuildy/helm-data-lake
maintainers:
- name: Thomas Decaux
  email: ebuildy@gmail.com
keywords:
- zeppelin
- data-lake
- big-data
- spark