replicaCount: 1

image:
  repository: apache/zeppelin
  tag: 0.9.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "zep"
  rbac:
    create: false

podAnnotations: {}

podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
     - ALL
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

networkPolicy:
  enabled: false
  extraEgressRules: []
  extraIngressRules: []

service:
  type: ClusterIP
  port: 8080
  rpcPort: 38853

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/affinity: "cookie"
    # nginx.ingress.kubernetes.io/session-cookie-name: "zep"
    # nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    # nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

zeppelin:
  server:
    jvmMemOptions: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Xms512m -Xmx512m -XX:MaxMetaspaceSize=512m

  interpreter:
    enabled: true
    thriftPort: 10000

logging:
  level: INFO
  syslog: {}
    #level: INFO
    #host:
    #port:
    #facility:
    #pattern:

notebookStorage:
  type: git
  repositorySecret: git-data-lake

sparkExternal:
  enabled: false
  master: spark://spark-master:7077

sparkEmbedded:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/spark
    pullPolicy: IfNotPresent
    tag: 2.4.5
  copyDirectory: /opt/bitnami/spark
  portWebUI: 4040
  ingress:
    enabled: false
  master: local[*] # k8s://https://kubernetes:443
