apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zeppelin.fullname" . }}
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zeppelin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-basics.yaml") . | sha256sum }}
        checksum/config-zep: {{ include (print $.Template.BasePath "/config-zeppelin-site.yaml") . | sha256sum }}
        checksum/config-int: {{ include (print $.Template.BasePath "/config-interpreter-settings.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "zeppelin.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zeppelin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      enableServiceLinks: false
      volumes:
        - name: config
          configMap:
            name: {{ include "zeppelin.fullname" . }}-config
            items:
            - key: log4j.properties
              path: log4j.properties
            - key: shiro.ini.template
              path: shiro.ini.template
        - name: site-config
          configMap:
            name: {{ include "zeppelin.fullname" . }}-site-config
            items:
            - key: zeppelin-site.xml
              path: zeppelin-site.xml
        - name: interpreter-config
          configMap:
            name: {{ include "zeppelin.fullname" . }}-interpreter
            items:
            - key: interpreter.json
              path: interpreter.json
        - name: config-volume
          emptyDir: {}
        - name: spark-config-volume
          emptyDir: {}
        - name: zep-tmp
          {{- if eq .Values.volumeTmp.type "emptyDir" }}
          emptyDir: {}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "zeppelin.fullname" . }}-tmp
          {{- end }}
        - name: zep-conf
          emptyDir: {}
        - name: zep-webapps
          emptyDir: {}
        - name: zep-notebooks
          {{- if eq .Values.volumeNotebooks.type "emptyDir" }}
          emptyDir: {}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "zeppelin.fullname" . }}-notebooks
          {{- end }}
        - name: zep-logs
          emptyDir: {}
        - name: etc-hack
          emptyDir: {}
        {{- if eq .Values.spark.driver.mode "local" }}
        - name: spark-home
          emptyDir: {}
        - name: spark-hive-warehouse
          emptyDir: {}
        - name: spark-derby-home
          emptyDir: {}
        - name: zep-repo
          emptyDir: {}
        - name: zep-ivy
          emptyDir: {}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
      initContainers:
      - {{- include "zeppelin.container.config" . | nindent 8 }}
      {{- if eq .Values.zeppelin.interpreter.mode "embedded" }}
      - {{- include "zeppelin.container.spark-init" . | nindent 8 }}
      {{- end }}
      - {{- include "zeppelin.container.fix-user" . | nindent 8 }}
      {{- if eq .Values.notebookStorage.type "git" }}
      - {{- include "zeppelin.container.git-init" . | nindent 8 }}
      {{- end }}
      containers:
      - {{- include "zeppelin.container.zeppelin" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
