kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "zeppelin.fullname" . }}-interpreter
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
data:
  {{- range $int, $v := .Values.zeppelin.interpreterSettings }}
  {{ $int }}.json : |-
    {{ $v | nindent 4 }}
  {{- end }}
  spark.json: |-
    {{- include "zeppelin.int.spark" . | nindent 4 }}