{{- if .Values.networkPolicy.enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "zeppelin.fullname" . }}
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "zeppelin.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Zeppelin server web UI
  - ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  {{- if eq .Values.zeppelin.interpreter.mode "embedded" }}
  # Spark web UI
  - ports:
    - protocol: TCP
      port: 4040
  {{- end }}
  {{- with .Values.networkPolicy.extraIngressRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.networkPolicy.extraEgressRules }}
  egress:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
