{{- if .Values.networkPolicy.enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "zeppelin.fullname" . }}
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "zeppelin.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Zeppelin server
  - ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  {{- if .Values.sparkEmbedded.enabled }}
  # Spark web UI
  - ports:
    - protocol: TCP
      port: 4040
  {{- end }}
  {{- if .Values.zeppelin.interpreter.enabled }}
  # Zeppelin RPC API
  - ports:
    - protocol: TCP
      port: {{ .Values.service.rpcPort }}
    from:
    - podSelector:
        matchLabels:
          zeppelin.apache.org/{{ template "zeppelin.fullname" . }}-interpreter: "true"
  {{- end }}
  {{- with .Values.networkPolicy.extraIngressRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  egress:
  {{- if .Values.zeppelin.interpreter.enabled }}
  # Zeppelin interpreter thrift
  - ports:
    - protocol: TCP
      port: {{ .Values.zeppelin.interpreter.thriftPort }}
    to:
    - podSelector:
        matchLabels:
          zeppelin.apache.org/{{ template "zeppelin.fullname" . }}-interpreter: "true"
  {{- end }}
  {{- with .Values.networkPolicy.extraEgressRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
