{{- if .Values.networkPolicy.enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "zeppelin.fullname" . }}
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "zeppelin.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "zeppelin.selectorLabels" . | nindent 10 }}
  - ports:
    - protocol: TCP
      port: 8080
  - ports:
    - protocol: TCP
      port: 12321
  - ports:
    - protocol: TCP
      port: {{ .Values.service.rpcPort }}
    - protocol: TCP
      port: 10000
  egress:
  - ports:
    - protocol: TCP
      port: 12321
  - ports:
    - protocol: TCP
      port: {{ .Values.service.rpcPort }}
    - protocol: TCP
      port: 10000
  - to:
    - podSelector:
        matchLabels:
          {{- include "zeppelin.selectorLabels" . | nindent 10 }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: master
          app.kubernetes.io/instance: spark-cluster
          app.kubernetes.io/name: spark
{{- end }}