{{- if .Values.networkPolicy.enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "zeppelin.fullname" . }}
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "zeppelin.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "zeppelin.selectorLabels" . | nindent 10 }}
  - ports:
    - protocol: TCP
      port: 8080
  - ports:
    - protocol: TCP
      port: 12321
  - ports:
    - protocol: TCP
      port: {{ .Values.service.rpcPort }}
    - protocol: TCP
      port: {{ .Values.interpreter.thriftPort }}
    from:
    - podSelector:
        matchLabels:
          {{ toYaml .Values.interpreter.labels | nindent 10 }}
  {{- with .Values.networkPolicy.extraIngressRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  egress:
  - ports:
    - protocol: TCP
      port: 12321
  - ports:
    - protocol: TCP
      port: {{ .Values.service.rpcPort }}
    - protocol: TCP
      port: {{ .Values.interpreter.thriftPort }}
    to:
    - podSelector:
        matchLabels:
          {{ toYaml .Values.interpreter.labels | nindent 10 }}
  {{- with .Values.networkPolicy.extraEgressRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}