apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeppelin.fullname" . }}
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.rpcPort }}
    targetPort: rpc
    protocol: TCP
    name: rpc
  {{- if .Values.sparkEmbedded.enabled }}
  - port: {{ .Values.sparkEmbedded.portWebUI }}
    targetPort: spark-ui
    protocol: TCP
    name: spark-ui
  {{- end }}
  selector:
    {{- include "zeppelin.selectorLabels" . | nindent 4 }}