{{- if .Values.networkPolicy.enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "zeppelin.fullname" . }}-stack
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "zeppelin.partOfLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "zeppelin.partOfLabels" . | nindent 10 }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- include "zeppelin.partOfLabels" . | nindent 10 }}
{{- end }}