kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "zeppelin.fullname" . }}-config
data:
  log4j.properties: |-
    log4j.rootLogger = {{ .Values.logging.level }}, stdout, {{- if .Values.logging.syslog }}, syslog{{- end }}

    log4j.appender.stdout = org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.Threshold = {{ .Values.logging.level }}
    log4j.appender.stdout.layout = org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%5p [%d] ({%t} %F[%M]:%L) - %m%n

    log4j.logger.org.apache.zeppelin.interpreter = {{ .Values.logging.level }}

    {{- with .Values.logging.syslog }}
    log4j.appender.syslog=org.apache.log4j.net.SyslogAppender
    log4j.appender.syslog.threshold={{ .level }}
    log4j.appender.syslog.syslogHost={{ .host }}:{{ .port }}
    log4j.appender.syslog.facility={{ .facility }}
    log4j.appender.syslog.layout=org.apache.log4j.PatternLayout
    log4j.appender.syslog.layout.conversionPattern={{ .pattern }}
    {{- end }}

  shiro.ini.template: |-
    [users]
    ADMIN_USER_NAME = ADMIN_PASSWORD, admin

    [main]
    sessionManager = org.apache.shiro.web.session.mgt.DefaultWebSessionManager
    cookie = org.apache.shiro.web.servlet.SimpleCookie
    cookie.name = JSESSIONID
    cookie.httpOnly = true
    sessionManager.sessionIdCookie = $cookie
    securityManager.sessionManager = $sessionManager
    securityManager.sessionManager.globalSessionTimeout = 86400000
    shiro.loginUrl = /api/login
    passwordMatcher = org.apache.shiro.authc.credential.PasswordMatcher
    iniRealm.credentialsMatcher = $passwordMatcher

    [roles]
    admin = *

    [urls]
    /api/version = anon
    /api/interpreter/setting/restart/** = authc
    /api/interpreter/** = authc, roles[admin]
    /api/configurations/** = authc, roles[admin]
    /api/credential/** = authc, roles[admin]
    #/** = anon
    /** = authc
