kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "zeppelin.fullname" . }}-site-config
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
data:
  zeppelin-site.xml: |-
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

    <configuration>

    {{- range $k,$v := .Values.zeppelin.properties }}
    <property>
      <name>{{$k}}</name>
      <value>{{$v}}</value>
    </property>
    {{- end }}
    <property>
      <name>zeppelin.server.rpc.hostName</name>
      <value>{{ template "zeppelin.fullname" . }}</value>
      <description>RPC server address</description>
    </property>

    <property>
      <name>zeppelin.server.rpc.portRange</name>
      <value>{{ .Values.service.rpcPort }}:{{ .Values.service.rpcPort }}</value>
      <description>RPC Server address port</description>
    </property>

    <property>
      <name>zeppelin.server.port</name>
      <value>{{ .Values.service.port }}</value>
      <description>Server port.</description>
    </property>

    <property>
      <name>zeppelin.server.ssl.port</name>
      <value>8443</value>
      <description>Server ssl port. (used when ssl property is set to true)</description>
    </property>

    {{- if eq .Values.notebookStorage.type "s3" }}
    <property>
      <name>zeppelin.notebook.s3.bucket</name>
      <value>{{ .Values.notebookStorage.path }}</value>
      <description>S3 bucket path</description>
    </property>
    <property>
      <name>zeppelin.notebook.storage</name>
      <value>org.apache.zeppelin.notebook.repo.S3NotebookRepo</value>
      <description>versioned notebook persistence layer implementation</description>
    </property>
    {{- else if eq .Values.notebookStorage.type "gs" }}
    <property>
      <name>zeppelin.notebook.gcs.dir</name>
      <value>gs://{{ .Values.notebookStorage.path }}</value>
      <description>GCS bucket path</description>
    </property>
    <property>
      <name>zeppelin.notebook.storage</name>
      <value>org.apache.zeppelin.notebook.repo.GCSNotebookRepo</value>
      <description>versioned notebook persistence layer implementation</description>
    </property>
    {{- else if eq .Values.notebookStorage.type "azure" }}
    <property>
      <name>zeppelin.notebook.azure.share</name>
      <value>{{ .Values.notebookStorage.path }}</value>
      <description>Azure FileShare name</description>
    </property>
    <property>
      <name>zeppelin.notebook.storage</name>
      <value>org.apache.zeppelin.notebook.repo.AzureNotebookRepo</value>
      <description>versioned notebook persistence layer implementation</description>
    </property>
    <property>
      <name>zeppelin.notebook.azure.connectionString</name>
      <value>DefaultEndpointsProtocol=https;AccountName={{ .Values.azureStorageAccountName }};AccountKey={{ .Values.azureStorageAccessKey }}</value>
      <description>Connection string to Azure File</description>
    </property>
    {{- else }}
    <property>
      <name>zeppelin.notebook.storage</name>
      <value>org.apache.zeppelin.notebook.repo.GitNotebookRepo</value>
      <description>versioned notebook persistence layer implementation</description>
    </property>
    {{- end }}

    </configuration>
