image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- extraVolumes Array to add extra volumes
extraVolumes: []
# - name: toto
#   emptyDir: {}

# -- extraVolumeMounts Array to add extra mount
extraVolumeMounts: []
# - name: toto
#   mountPath: /app/toto

# -- spec for spark ivy volume (string template)
volumeSparkIvy: |-
  emptyDir: {}

# -- spec for spark work volume (string template)
volumeSparkWork: |-
  emptyDir: {}

# -- spec for tmp volume (string template)
volumeTmp: |-
  emptyDir: {}

# -- extra env variables
extraEnvVars: {}

nodeSelector: {}

tolerations: []

affinity: {}

sparkConfLogging:
  # -- log level for root
  rootLevel: debug
  # -- log level for thrift server
  thriftServerLevel: warn
  # -- log level for repl
  replLevel: warn

sparkExtraDefaults: |
  spark.master: k8s://https://kubernetes.default.svc
  spark.submit.deployMode: client

  # K8S
  spark.kubernetes.namespace: dev-steam

  spark.kubernetes.authenticate.driver.serviceAccountName: zep-zeppelin
  spark.kubernetes.driver.podTemplateFile: /opt/spark/k8s/executor-pod-template/pod.yaml
  spark.kubernetes.driver.limit.cores: 1

  spark.kubernetes.executor.podTemplateFile: /opt/spark/k8s/executor-pod-template/pod.yaml
  spark.kubernetes.executor.limit.cores: 2

  spark.kubernetes.container.image: spark:latest
  spark.kubernetes.file.upload.path: hdfs://10.100.42.2:8020/tmp/zep-spark-k8s/

  spark.kubernetes.authenticate.submission.clientKeyFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  spark.kubernetes.driver.deleteOnTermination: false
  spark.kubernetes.executor.podNamePrefix: zep