image:
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- extraVolumes Array to add extra volumes
extraVolumes: []
# - name: toto
#   emptyDir: {}

# -- extraVolumeMounts Array to add extra mount
extraVolumeMounts: []
# - name: toto
#   mountPath: /app/toto

# -- spec for spark ivy volume (string template)
volumeSparkIvy: |-
  emptyDir: {}

# -- spec for spark work volume (string template)
volumeSparkWork: |-
  emptyDir: {}

# -- spec for tmp volume (string template)
volumeTmp: |-
  emptyDir: {}

# -- extra env variables
extraEnvVars: {}

nodeSelector: {}

tolerations: []

affinity: {}

# -- to create a config-map with spark conf, to share with spark driver
sparkConf:
  # -- enable or not config-map with spark conf
  enabled: false

  # -- logging stuff
  logging:
    # -- log level for root
    rootLevel: info
    # -- log level for thrift server
    thriftServerLevel: warn
    # -- log level for repl
    replLevel: warn

  # -- edit spark-defaults.conf
  defaults: |
    spark.master: k8s://https://kubernetes.default.svc
    spark.submit.deployMode: client
