{{- range $i, $binding := .Values.rabbitmq.bindings }}
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: {{ printf "%s-%s" (include "rabbitmq.fullname" $) $binding.name | lower | replace "." "-" | replace "_" "-" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "rabbitmq.labels" $ | nindent 4 }}
spec:
  {{- $binding.spec | toYaml | nindent 2 }}
  rabbitmqClusterReference:
    name: {{ include "rabbitmq.fullname" $ }}
---
{{- end }}
