{{- range $i, $exchange := .Values.rabbitmq.exchanges }}
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: {{ printf "%s-%s" (include "rabbitmq.fullname" $) $exchange.name | lower | replace "." "-" | replace "_" "-" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "rabbitmq.labels" $ | nindent 4 }}
spec:
  name: {{ $exchange.name }}
  {{- $exchange.spec | toYaml | nindent 2 }}
  rabbitmqClusterReference:
    name: {{ include "rabbitmq.fullname" $ }}
---
{{- end }}
