{{- range $i, $permission := .Values.rabbitmq.permissions }}
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: {{ include "rabbitmq.fullname" $ }}-{{ $permission.name }}
  labels:
    {{- include "rabbitmq.labels" $ | nindent 4 }}
spec:
  {{- $permission.spec | toYaml | nindent 2 }}
  rabbitmqClusterReference:
    name: {{ include "rabbitmq.fullname" $ }}
---
{{- end }}
