{{- range $i, $queue := .Values.rabbitmq.queues }}
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: {{ include "rabbitmq.fullname" $ }}-{{ $queue.name }}
  labels:
    {{- include "rabbitmq.labels" $ | nindent 4 }}
spec:
  name: {{ $queue.name }}
  {{- $queue.spec | toYaml | nindent 2 }}
  rabbitmqClusterReference:
    name: {{ include "rabbitmq.fullname" $ }}
---
{{- end }}
