{{- range $i, $queue := .Values.rabbitmq.queues }}
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: {{ printf "%s-%s" (include "rabbitmq.fullname" $) $queue.name | lower | replace "." "-" | replace "_" "-" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "rabbitmq.labels" $ | nindent 4 }}
spec:
  name: {{ $queue.name }}
  {{- $queue.spec | toYaml | nindent 2 }}
  rabbitmqClusterReference:
    name: {{ include "rabbitmq.fullname" $ }}
{{- end }}