{{- if .Values.extraService.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.extraService.nameOverride }}
  name: {{ .Values.extraService.nameOverride }}
  {{- else }}
  name: {{ include "rabbitmq.fullname" . }}-extra
  {{- end }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
  {{- with .Values.extraService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.extraService.type }}
  {{- with .Values.extraService.extraSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: http-stats
      port: 15672
      targetPort: stats
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
{{- end }}
