apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-cluster.fullname" . }}-master
  labels:
    {{- include "spark-cluster.labels" . | nindent 4 }}
    {{- include "spark-cluster-master.labels" . | nindent 4 }}
  {{- with .Values.master.service.annotations }}
  annotations: {{ . | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.master.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.cluster.port }}
      targetPort: cluster
      protocol: TCP
      name: cluster
  {{- with .Values.master.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  selector:
    {{- include "spark-cluster.selectorLabels" . | nindent 4 }}
    {{- include "spark-cluster-master.labels" . | nindent 4 }}
