{{- if .Values.networkPolicy.enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.names.fullname" . }}-master
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: master
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: master
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels: {{- include "common.labels.matchLabels" . | nindent 10 }}
    - podSelector:
        matchLabels:
          spark.apache.org/cluster: allow
  - ports:
    - protocol: TCP
      port: {{ .Values.master.webPort }}
  egress:
  - to:
    - podSelector:
        matchLabels: {{- include "common.labels.matchLabels" . | nindent 10 }}
    - podSelector:
        matchLabels:
          spark.apache.org/cluster: allow
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.names.fullname" . }}-worker
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: worker
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels: {{- include "common.labels.matchLabels" . | nindent 10 }}
    - podSelector:
        matchLabels:
          spark.apache.org/cluster: allow
  ingress:
  - ports:
    - protocol: TCP
      port: {{ .Values.worker.webPort }}
  - from:
    - podSelector:
        matchLabels: {{- include "common.labels.matchLabels" . | nindent 10 }}
    - podSelector:
        matchLabels:
          spark.apache.org/cluster: allow
{{- end }}