apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-cluster.fullname" . }}-worker
  labels:
    {{- include "spark-cluster.labels" . | nindent 4 }}
    {{- include "spark-cluster-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spark-cluster.selectorLabels" . | nindent 4 }}
    {{- include "spark-cluster-worker.labels" . | nindent 4 }}
