name: Lint and Test Charts

on: [pull_request]
 
jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Add helm deps
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.0.0
        
      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct-lint.yaml

